### ISSUE TITLE
Set minimum charging current for SOC dependent charge current limiting

### ISSUE THREAD

**Issue by tanelvakker** [shining-man/bsc_fw#101]
Currently it allows the charge current to go down to 0. 
<img width="592" alt="Screenshot 2024-03-31 at 23 02 48" src="https://github.com/shining-man/bsc_fw/assets/26738629/5d86761d-f317-456b-bace-92a3cb681cc0">
Would it make sense to define minimum charging current as well? I would still allow at least 1A current so the balancer can do it's work, but keep the SOC up.

**Comment by shining-man** [comment]
It's a good idea.
I'll add the setting for a minimum charging current.

**Comment by tueftler0** [comment]
@tanelvakker Integrated now. Please test the newest beta. Thank you

**Comment by tueftler0** [comment]
@shining-man No reply since three weeks from TO. Maybe the issue can be closed now -> Released

**Comment by tanelvakker** [comment]
It works fine. Can be closed

**Comment by tueftler0** [comment]
Nice to hear that! You can close the issue yourself by clicking the button at the bottom.
