### ISSUE TITLE
Web UI übernimmt keine Daten

### ISSUE THREAD

**Issue by 3RROR-TINO** [shining-man/bsc_fw#114]
Hab es auf einem ESp 32 Wroom komm auf die Web Ui aber er übernimmt die eingegebenen Daten nicht???

**Comment by shining-man** [comment]
Bitte ein paar mehr Details. Sonst wird es schwierig zu helfen.
- Welcher ESP32 Wroom genau (Hersteller, ...)?
- Welches Netzeil?
- Eine Kopie des Logs, nach einem Speichervorgang (Als Dateianhang)
- Hast du es nach der Anleitung im wiki geflasht?
- Welche Version?
- Alle Infos die dir sonst noch einfallen

**Comment by shining-man** [comment]
Geschlossen da keine Rückmeldung
