### ISSUE TITLE
Heltec 4A active balancer (Neey) ?

### ISSUE THREAD

**Issue by Starter4711** [shining-man/bsc_fw#116]
Hallo,
sollte sich der Heltec auch verbinden lassen? schaffe es leider nicht.
Heltec GW-24S4EB
HW-3.2.0
SW: ZH-1.2.4

BG

**Comment by Starter4711** [comment]
Hatte die Mac ID mit Großbuchstaben eingegeben, jetzt fkt. es.
Können die Sleep u Equlization Voltage nicht per Mqtt gelesen/geschrieben werden?

**Comment by shining-man** [comment]
Schreiben der Einstellungen geht nur über die Weboberfläche

**Comment by Starter4711** [comment]
OK, danke.
