### ISSUE TITLE
Neey Mqtt Beschreibung?

### ISSUE THREAD

**Issue by Starter4711** [shining-man/bsc_fw#117]
Hallo, wäre eine Beschreibung der Variablen vorhanden?
zBsp. balancingactive ist eine Zahl von 0-10? welche Zahl steht für welchen Zustand
<img width="954" alt="Bildschirmfoto 2024-05-26 um 19 57 33" src="https://github.com/shining-man/bsc_fw/assets/15359915/d9cff9f1-8324-4571-9b7f-cac1326735c3">

**Comment by shining-man** [comment]
Beim NEEY werden nicht alle Felder mit Werten befüllt, da er diese nicht liefert.
"valid" gibt an, ob das Device die letzten 5 Sekunden Daten an den BSC gesendet hat, wenn nicht geht es auf 0.

balancingActive:
![grafik](https://github.com/shining-man/bsc_fw/assets/109786660/27f90e3a-ae9a-40fc-b773-5046e7b87a17)

**Comment by Starter4711** [comment]
Danke!
