### ISSUE TITLE
Erneutes Senden aller Datenpunkte bei MQTT reconnect und manuellem Trigger Event

### ISSUE THREAD

**Issue by tueftler0** [shining-man/bsc_fw#120]
Normalerweise wurde bisher alle ca 30s alle Topics via MQTT übertragen, auch wenn sich keine Wertänderung ergab (glaube ich zumindest).
Mir fehlen derzeit die zyklischen Trigger-Übertragungen seid dem neuen Release.
In der RestAPI sind sie sichtbar.

**Comment by shining-man** [comment]
Die Trigger wurde auch vorher nicht zyklisch übertragen. Hier hat sich nichts geänert.

**Comment by tueftler0** [comment]
Danke fürs Feedback.
Okay, dann wäre es toll, wenn man dies in Zukunft mal mit integrieren würde.
HomeAssistant beispielsweise hätte gerne alle x Minuten eine Message, ansonsten gehen die States auf Unbekannt:
![image](https://github.com/shining-man/bsc_fw/assets/35748555/c88dbab3-e304-4cd9-8b0c-ac19167fb48a)

**Comment by shining-man** [comment]
Ansich finde ich es nicht schön etwas einzubauen nur um irgendwelche System mit etwas zu befriedigen, was sie morgen vielleicht schon wieder ändern. 
Macht es wirklich Sinn Nachrichten zyklisch zu versenden, auch wenn sie sich nicht geändert haben? Wäre es nicht Sinnvoller man würde den QoS erhöhen?
Ansich kommt es auf die 10 Nachrichten nicht an, aber ich wollte genrell den Traffic senken und andere Werte auch nur bei Änderung senden, das würde dann vmtl. an mehr Stellen zu diesem Verhalten führen. Gut, dass wir auf das Thema zu sprechen kommen.

**Comment by tueftler0** [comment]
Ich kann Dich da schon verstehen. Jedoch kann es ja auch gut sein, dass der MQTT-Broker einmal neu gestartet wird oder ein Repeater ausfällt (usw) und in dieser Zeit ein Trigger oder sonstiger Wert sich ändert.
Das würde dann bis zur nächsten Änderung nie auffallen.
Daher finde ich es schon sinnvoll, wenn man alle Werte alle 30 Sekunden oder so einmal rüber sendet.
Auch könnte man in dieser Funktion das HA-Discovery integrieren, da hier ja scheinbar beim Anlegen immer alle via MQTT möglichen Daten vorliegen müssen. Das hatte glaub mal NSC heraus gefunden.

**Comment by shining-man** [comment]
HA-Discovery wird vmtl. nie den Weg in den BSC finden. Das ist einfach zu viel Overhead. 
Einen ausfallenden Repeater könnten man mit QoS 1 auch feststellen, denn dann muss die Nachricht mindestens einmal zugestellt werden.
Zum Neustart: Es macht mehr Sinn alle Nachrichten erneut zusenden, wenn es zu einem reconnect kommt.

Ansich möchte ich die Flut der Nachrichten etwas ein dämmen. Ich möchte auf ein dynamisches Konzept umsteigen, bei dem es keine festen Sendezeiten mehr gibt, sondern nur bei Änderung und Gewichtung der Werte gesendet wird. 
Wenn das BPN einmal kommen sollte, dann gibt es pro BMS fast 40 Temperaturwerte mehr. Wenn ich die alle zyklisch sende, dann gibt es keinen 30s Intervall mehr, sondern ich muss langsamer werden. Daher nehme ich jetzt ungern Werte in das zyklische Senden auf.

**Comment by tueftler0** [comment]
HA-Discovery könnte man ja auch einmalig über das Webfrontend, oder bei jedem Neustart triggern - Aber nun ja erst einmal egal ;)

QoS 1 wäre definitiv sinnvoll, wenn ein Senden aller Werte umgangen werden soll.
Alle Werte nur bei einem Reconnect senden wäre schon eine Lösung.
Was man genau gegen dieses "Unbekannt" machen kann werde ich mal nachforschen.
Blöd ist eben, wenn man nach true/false triggert und dann ein unknown bekommt :)

**Comment by tueftler0** [comment]
Korrektur der Aussage:
HomeAssistant führt den Trigger (Sensor Component) als "unavailable" wenn bis zu dem Zeitpunkt über MQTT kein Wert übermittelt wurde.
Grundsätzlich okay, wenn der State ja nicht sicher anzunehmen ist.
Daher ist Deine Idee mit dem Senden aller Datenpunkte bei reconnect wahrscheinlich passend.

Ein Timeout für den Sensor ist zwar konfigurierbar, aber standardmäßig deaktiv.

**Comment by tueftler0** [comment]
Zusätzlich zum Senden bei Reconnect bräuchte man noch eine Möglichkeit manuell das Senden zu aktivieren.
Wenn man z.B. nur alle YAML-Dateien neu einlesen lässt, oder Sensoren neu benennt, dann wäre es gut einmalig alles auf den aktuellen Stand setzen zu können.
Vorstellbar wäre z.B. ein Trigger (VTrigger?) über MQTT oder Tastendruck in der GUI.

**Comment by shining-man** [comment]
Ich werde jetzt vorerst einmal die Trigger mit in dem zyklischen Sendeintervall aufnehmen. Damit sollte sich das Problem und die Notwedigkeit des Buttons erledigt haben?

**Comment by a-wolter** [comment]
> Ich werde jetzt vorerst einmal die Trigger mit in dem zyklischen Sendeintervall aufnehmen. Damit sollte sich das Problem und die Notwedigkeit des Buttons erledigt haben?

Ich denke so würde es passen. Es kann nämlich tatsächlich ein Problem sein, da der mqtt Status wie von @tueftler0 erwähnt, nicht immer passt. 

Beispiel: Trigger wurde aktiv, mqtt reconnect und mqtt Status hat sich nicht verändert obwohl der trigger low gegangen ist in der Zwischenzeit:

![IMG_4988](https://github.com/user-attachments/assets/9a700170-a089-441e-9c7b-9924505490d8)
![IMG_4990](https://github.com/user-attachments/assets/ae3b9ca9-bf82-4a4d-8274-492c571e3001)

So ist er nun über Tage als high im mqtt (BMS Verbindungsverlust)

**Comment by shining-man** [comment]
The change/extension is included in version 0.7.0.
