### ISSUE TITLE
Warnings aus Seplos werden als Error an Victron weitergeleitet

### ISSUE THREAD

**Issue by SladeTheLeveller** [shining-man/bsc_fw#123]
Das Seplos sendet bei einer Schwelle x eine Warnung, über diese Warnungsschwelle muss es 30 Minuten bleiben, um 100% SOC anzuzeigen. Die Warning wird als Error im BSC interpretiert, sowohl in MQTT als auch im Victron selber und führt damit zum Ladungsabbruch.

**Comment by shining-man** [comment]
Wie heißt die Warnung?
Kann diese Warnung im Seplos eingestellt werden, oder ist die fest?

**Comment by shining-man** [comment]
"High voltage alarm for total voltage" werte ich als Warnung und 
"Overvoltage protection for total voltage" als Error. Da sehe ich erst einmal keinen Fehler.
Ums das Problem eingrenzen zu können braucht es mehr Infos:
- Welchen Fehler meldet der Wechselrichter?
- Was kommt über MQTT als Fehler?
- Welche Fehler zeigt das BMS selber an?

**Comment by RRonGit** [comment]
Ich habe mal versucht die Meldungen zusammen zu tragen, weis nicht ob das so reicht.
Die Meldungen werden ab einer Zellspannung >3.5V oder ab einer Gesamtspannung >56V angezeigt (ist gem. Seplos der "Over voltage warning" Bereich.

**_WR:_**
![ovw_victron](https://github.com/shining-man/bsc_fw/assets/11077414/5384e45a-7a30-4ec1-a6cc-6352b0247cc6)

**_MQTT:_**
![ovw_mqtt_g](https://github.com/shining-man/bsc_fw/assets/11077414/3feae982-f48a-423a-b04b-617445e4c4c5)

![ovw_mqtt_inverter](https://github.com/shining-man/bsc_fw/assets/11077414/3bb33936-9625-45d4-9e8f-b7de7a087902)

_**BMS:**_
![ovw_bms](https://github.com/shining-man/bsc_fw/assets/11077414/7a882e79-c7b7-44c0-ab5d-f463902f4a2e)

_**BSC:**_
![ovw_bsc_g](https://github.com/shining-man/bsc_fw/assets/11077414/de248936-a183-48d5-acfe-64590b5edf87)

**Comment by shining-man** [comment]
@RRonGit Danke für die Infos. Hab jetzt den Fehler gefunden.

**Comment by RRonGit** [comment]
@shining-man wird die entsprechende Fehlerbehebung im nächsten Release drinnen sein?

**Comment by shining-man** [comment]
> @shining-man wird die entsprechende Fehlerbehebung im nächsten Release drinnen sein?

Ja. Aber das neue Release wird noch dauern.
Im Branch [new_features_24-2](https://github.com/shining-man/bsc_fw/tree/new_features_24-2) ist es mit drin. Der ist aber nicht stable.

**Comment by RRonGit** [comment]
@shining-man Ok, alles klar. Freue mich jetzt schon aufs neue Release und auf jedes weitere. Super Projekt, danke für deine tolle Arbeit.

**Comment by shining-man** [comment]
The change/extension is included in version 0.7.0.
