### ISSUE TITLE
fehlende MQTT Datenpunkte

### ISSUE THREAD

**Issue by RRonGit** [shining-man/bsc_fw#124]
Der BSC läuft soweit mit der Hardware 2.5 und der Firmware v0.6.0
Der BSC liest zwei Seplos Akkus aus. Seplos BMS V16 (10E) Software Version: 16.6

Frage zu den übermittelten MQTT Daten:

Ich bekomme die Daten der zwei Akkus per MQTT, was mir fehlt sind die folgenden Datenpunkte in MQTT:

Balancing active
bmsStateFETs
Max. voltage cellnumber
Min. voltage cellnumber

Im Webgui werden die Datenpunkte entsprechend angezeigt.

**Comment by tueftler0** [comment]
bmsStateFETs ist drin - Aber gesplittet "stateCharge" und "stateDischarge"

**Comment by shining-man** [comment]
The change/extension is included in version 0.7.0.
