### ISSUE TITLE
Balancing Seplos wird nicht angezeigt

### ISSUE THREAD

**Issue by RRonGit** [shining-man/bsc_fw#125]
Der BSC läuft mit der Hardware 2.5 und der Firmware v0.6.0
Der BSC liest zwei Seplos Akkus aus. Seplos BMS V16 (10E) Software Version: 16.6

Wenn die Seplos Akkus balancen wird dies vom BSC nicht erfasst, resp. im Webgui nicht angezeigt.

![image](https://github.com/shining-man/bsc_fw/assets/11077414/0c898bc4-46c9-4d90-9326-c1ecbb241360)

Balancing active bleibt auf 0

Kann dies allenfalls noch gefixt werden?

**Comment by shining-man** [comment]
The change/extension is included in version 0.7.0.
