### ISSUE TITLE
Feature 16 Seplos Packs 

### ISSUE THREAD

**Issue by Mights001** [shining-man/bsc_fw#132]
Hallo Leute, 
könnt ihr den Source Code anpassen das 16 Packs möglich sind bzw. auch die Begrenzungen für Laden und Entladen höher stellen auf über 1000A. 
Mit der Anlage gehen zwar nur 960A aber wir erweitern ev. bald und dann ist die Grenze eine Hürde. 
Auch der Live View für die BMS wär toll wenn ihr erweitern könntet. 

Ich habe die Grenzen selber schon angehoben in de params_py.h ev. würde es wer anderer auch noch brauchen. 

Danke!

**Comment by shining-man** [comment]
Im nächsten Release ist eine Änderung geplant damit mehr serielle Devices verbudnen werden können.
Dafür wirst du dann aber weniger BT Devices verbinden können.

**Comment by shining-man** [comment]
The change/extension is included in version 0.7.0.
