### ISSUE TITLE
Onewire - Websettings: Istwerte anzeigen

### ISSUE THREAD

**Issue by kmn13** [shining-man/bsc_fw#14]
Zum einfacheren Fehlersuche und Setup, gerade auch im Hinblick auf die Offseteinstellungen wäre es hilfreich auch die aktuell gemessenen Temperaturen anzuzeigen.

**Comment by kmn13** [comment]
Ich denke auch dass eine gesonderte Seite ausreichend ist.

Kann mir das aber auch mal ansehen und in einen Branch stopfen.

**Comment by shining-man** [comment]
Funktion ist im Release v0.3.0 enthalten.
