### ISSUE TITLE
BMS Temperatur Sensor

### ISSUE THREAD

**Issue by a-wolter** [shining-man/bsc_fw#143]
Laut WebUI kann ich bei Auswahl "BMS" nur 0-2 als Temp. Sensor festlegen. Ich konnte problemlos "4" eintragen, der Wert welcher an VenusOS gesendet wird ändert sich allerdings nicht.
Zudem ist nicht ganz klar, welcher Sensor aus welchem Pack nun übertragen wird. Ich vermute es ist ein Wert aus dem Pack mit der niedrigsten ID, da die Temperatur passen würde.

Mit z.B. 5 JK Inverter BMS im Daisy-Chain an Serial 2 sollten min. auch 5 Sensoren zur Verfügung stehen.
Evtl. sogar mehr, da über die JK App pro Pack 4 Sensoren (5 mit MOS Temp) angezeigt werden

![grafik](https://github.com/user-attachments/assets/da86c681-9798-4770-88ac-36dbb4c5465f)

Der Wert für die min cell temp ist falsch
![grafik](https://github.com/user-attachments/assets/a24cc2e6-c9bc-4334-8676-028d7d8860b2)

Getestet mit JK Inverter BMS an Serial2 im Daisy-Chain. FW 15.17

**Comment by shining-man** [comment]
Werte kannst du von 0-63 eintragen. Aber für BMS ist nur 0-2 gültig. Dies hat den Grund, dass in der internen Datenstruktur des BSC platz für 3 Temperaturen ist. Wenn ein BMS mehr als drei Temperaturen liefert, dann nehme ich immer die ersten drei.
Aus diesen drei Temperaturen wird dann auch die Min./Max.-Temp genommen. Ich vermute, dass eine der Temperaturen 0 ist und daher ist die Min.-Temp auch 0. Das wäre von daher erst einmal richtig.

Man muss jetzt schauen, welche drei Temperaturen sinn ergeben.

**Comment by a-wolter** [comment]
Das kann ich bestätigen 
![grafik](https://github.com/user-attachments/assets/6465c77b-bf21-4b87-bf0b-fc1650429c43)

**Comment by a-wolter** [comment]
Hier der Vergleich von JK App zu /restapi

![IMG_4203](https://github.com/user-attachments/assets/94cc1054-73e1-4195-baf1-f0f9e93aef8a)
![IMG_4202](https://github.com/user-attachments/assets/5ca276e7-10e0-4231-a9b2-8ffe3791a084)

**Comment by a-wolter** [comment]
Funktioniert ab der 0.6.1_T7
