### ISSUE TITLE
Autobalance Funktion erweitert. Timout -> Erneuter Start am nächsten Tag

### ISSUE THREAD

**Issue by tueftler0** [shining-man/bsc_fw#147]
Es wäre gut wenn ein Timeout den Balancing-Zyklus am nächsten Tag direkt wieder probieren würde.
Ungeachtet einer eingestellten Zykluszeit.

**Comment by shining-man** [comment]
Man könnte so etwas schon einbauen, doch wie oft will man das Spiel treiben? 
Sollte man hier evtl. einen Timeoutcounter einbauen der z.B. über MQTT verteilt wird?

**Comment by shining-man** [comment]
The change/extension is included in version 0.7.0.
