### ISSUE TITLE
Fix Victron Smartshunt an beliebigem Serial bzw Serial Extension

### ISSUE THREAD

**Issue by D3R-ST3FAN** [shining-man/bsc_fw#161]
Die Victron Smart-Shunts sind im Moment nur eingeschränkt nutzbar.

Ziel sollte es sein, die BSC Firmware anzupassen um eine beliebige Anzahl Smartshunts an beliebigen Serial Ports (inkl. der Extension) nutzen zu können.

**Comment by shining-man** [comment]
Hier gibt es Limitierung wo man erst schauen muss ob es einen Weg gibt das ganze per Software zu lösen.

**Comment by shining-man** [comment]
Durch die Umstellung auf den HEX-Mode (Commit: 0a42def2ed3f95b017ed5d82c99751cb0a5a2610) und Änderungen im Zuger der Umstellung auf das Data-Mapping sollte das jetzt möglich sien. 
Die Änderung ist im nächsten Release enthalten.

**Comment by shining-man** [comment]
The change/extension is included in version 0.7.0.
