### ISSUE TITLE
Unterstützung BT JK Inverter BMS

### ISSUE THREAD

**Issue by D3R-ST3FAN** [shining-man/bsc_fw#162]
Im Moment werden die JK Inverter BMS via Bluetooth nicht unterstützt.

Das JK BT Protokoll des Inverter BMS sollte unterstützt werden.

**Comment by tueftler0** [comment]
Ein BMS mit Bluetooth anzubinden macht aus Sicherheits-Sicht wenig Sinn.
Für eine störsichere Verbindung, vor allem zu einem BMS, sollten Kabel genutzt werden.
Daher wird es wohl nicht in den BSC einfließen.

**Comment by shining-man** [comment]
Da Bluetooth nicht zum Konzept des BSC passt, wird es, Stand heute, kein weiteres BT-Device geben. Der NEEY geht nicht anders, da er keine serielle Schnittstelle hat.
