### ISSUE TITLE
Alarmtrigger funktionieren nicht für Slave BMS (Daisy-Chain mit JK Inverter BMS)

### ISSUE THREAD

**Issue by D3R-ST3FAN** [shining-man/bsc_fw#170]
Beim testen  ist mir aufgefallen, dass die Alarmregeln Trigger NICHT für die Daisy Chain BMS greifen (FW v0.6.1_t8 3xJK Inverter an Serial2). 
Serial 2 funktioniert. 
Serial 3-4,  also die anderen BMS triggern nicht. 
Getestet mit Spannungsüberwachung Zelle Min/Max.

Entweder sollte (in meinem Fall Serial 2) alle Slaves mit einbeziehen oder das Slave Handling mit dem Mapping auf Serial 3-x muss korrigiert werden.

**Comment by shining-man** [comment]
Das Problem sollte jetzt behoben sein.
