### ISSUE TITLE
Total voltage and total current of the Victron Smart Shunt are wrong

### ISSUE THREAD

**Issue by toptec01** [shining-man/bsc_fw#174]
Hello,
the format of voltage and current in MQTT are different by BMS and Victron Smart Shunt.
Example:
- Serial 0 Victron SmartShunt
totalVoltage = 5218
totalCurrent = -4686

- Serial 2 JK-Inverter-BMS
totalVoltage = 52.220001
totalCurrent = -10.730000

**Comment by dominikfe** [comment]
Hi! I propose a value in Volt and V.mV format for everything voltage. Cheers

**Comment by shining-man** [comment]
The title is a bit confusing, because only the total voltage and total current of the Victron Smart Shunt are wrong.

**Comment by shining-man** [comment]
The change/extension is included in version 0.7.0.
