### ISSUE TITLE
Schrägnaht entfernen Orca Slicer

### ISSUE THREAD

**Issue by Laendler** [shining-man/bsc_fw#187]
Hallo

Ich soll einen Zylinder drucken mit 150 mm Durchmesser, aber die Z Naht versaut mir den Druck. 
Jetzt habe ich hier schon einen Bericht gefunden in dem auch eine Datei zum Herunterladen enthalten war. 
Leider ist sie nicht mehr verfügbar. 
Kann mir vielleicht einer helfen (auf Deutsch, da mein English Grottenschlecht ist), damit ich mein Problem beheben kann

Danke im Voraus
Karl

**Comment by tueftler0** [comment]
Hallo Karl.
Dieses Problem hat nicht wirklich etwas mit dem BSC zu tun.
Bitte wende Dich diesbezüglich an andere Stellen - Da gibt es ja etliche für 3d-Druck.
Such mal z.B. nach "mpoxDE 3d-Druck Discord".

@shining-man Kann denke ich geschlossen werden.
