### ISSUE TITLE
Victron Smart Shunt - Falsche Sklierung der Werte über MQTT

### ISSUE THREAD

**Issue by TheSmartGerman** [shining-man/bsc_fw#188]
In der LiveView übersicht werden die richtigen Werte angezeigt, über MQTT wird der Wert falsch übermittelt. Es muss um Faktor 100 geteilt werden. Umrechung A / mA wäre Faktor 1000

Beim mir läuft aktuell: Battery Safety Controller   V0.7.0_T11

Im Vergleich zum BMS sollte jeweils die geleiche Skalierung übermittelt werden. 

![grafik](https://github.com/user-attachments/assets/470a73e6-75bd-4a19-8e37-2fca648420a8)
![grafik](https://github.com/user-attachments/assets/f2abd6f5-0eca-4b23-9d4f-aec9817c722e)
![grafik](https://github.com/user-attachments/assets/e22f5af8-1a2d-4ce1-829d-170dffa81d2d)

**Comment by shining-man** [comment]
Es gibt zu dem Problem schon das Issue #174

**Comment by TheSmartGerman** [comment]
ups, sorry übersehen... alles klar!
