### ISSUE TITLE
Nächstes Release

### ISSUE THREAD

**Issue by peterfroehlich** [shining-man/bsc_fw#189]
Hallo, ich weiss das die meisten Entwicklung im Discord stattfindet, aber es wäre wirklich schön mal wieder ein stable Release hier auf Github zu sehen. Ganz lieben Dank!

**Comment by shining-man** [comment]
Das nächsten Major Release ist für Ende 2024 / Anfang 2025 geplant. Ist also nicht mehr so lange bis dahin ;-)
Auf Discord gibt es immer die Teststände, aber stable kommt ganz normal auf github.

**Comment by tueftler0** [comment]
@peterfroehlich Issue bitte schließen
