### ISSUE TITLE
Heizungsmeldung bei Seplos BMS generiert über CAN eine Warning

### ISSUE THREAD

**Issue by tueftler0** [shining-man/bsc_fw#191]
Wie im Discord besprochen wird bei einer Heizungs-Aktivierung über RS485 ein "Cell Low Temperatur Heating" in Richtung BSC gesendet. Dies ist ein normaler Vorgang bei Nutzern, die eben diese Funktionalität der Heizung nutzen.
Meiner Meinung nach sollte das weder als Warning, noch als Error verstanden werden.

Da diese Meldung über den CANbus des BMS ohnehin nicht versandt wird, steht nahe, dass es nur als Info für die Parametrisierungs-Software des Seplos integriert wurde.
Da z.B. Victron daher hiervon bei direkt Anschluss nichts mit bekommt und dies daher nicht kennt, würde ich die Meldung im BSC mit einem Kommentar im Source ignorieren und nicht weiter geben.

Wenn es zu kalt werden würde, gäbe es ja dementsprechende weitere Meldungen [Copy von Chris-X]:
Warnings:
22    Charging low temperature warning    10.0    ℃
30    Discharge low temperature warning    4.0    ℃ 
Errors:
26    Charging under-temperature protection    4.0    ℃
32    Discharge over temperature protection    45.0    ℃

**Comment by shining-man** [comment]
Im commit c299960 gefixt
