### ISSUE TITLE
BSC fällt Daly ab und an in das Wort

### ISSUE THREAD

**Issue by tueftler0** [shining-man/bsc_fw#194]
Das Daly BMS sendet ab und an plötzlich den Stream in einer unterschiedlichen Paketlänge.
Dadurch kollidiert das Senden des nächsten Befehls vom BSC mit diesem.
Das BSC muss unbedingt warten bis das Daly seine Dinge kundgetan hat.
Sonst gibt es immer einen Checksum-Fehler.

PS.: Das vorhergehende Daly-Timing kann eigentlich auch wieder integriert werden, wenn nicht schon geschehen.

**Comment by shining-man** [comment]
Die unterschiedliche Länge wird im Grunde schon immer beachtet. Das Problem tritt nur auf, wenn das Daly einen "Mist" sendet, da ich dann nicht warte bis er fertig ist mit des Senden des "Mists" ist, sondern eben nur abwarte bis der Timeout abgelaufen ist. Das werde ich fixen. Einen Checksum Fehler wird es aber dennoch geben, denn der kommende "Mist" ändert sich dadurch nicht.

**Comment by shining-man** [comment]
The change/extension is included in version 0.7.0.
