### ISSUE TITLE
Hysterese bei Spannungsüberwachung Zelle Min/Max unter Alarmregeln

### ISSUE THREAD

**Issue by Knofn** [shining-man/bsc_fw#200]
Aufgrund der Zell Regeneration beim Entladen kommt es zu etlichen Trigger high/low Umschaltungen.
Das gleiche gilt beim Laden. 
Da würde eine Hysterese min/max wie bei **Spannungsüberwachung Gesamt Min/Max** Abhilfe schaffen

:)

**Comment by D3R-ST3FAN** [comment]
meinst du sowas?
https://github.com/shining-man/bsc_fw/issues/171
Das wird kommen.

**Comment by Knofn** [comment]
sorry hab ich übersehen

**Comment by tueftler0** [comment]
> Das wird kommen.
Ist in der gerade erschienenen beta drin
