### ISSUE TITLE
Ladestrom begrenzen bei Überschreitung von Charge current per pack

### ISSUE THREAD

**Issue by Knofn** [shining-man/bsc_fw#201]
Bei unterschiedlichen Batterie Packs kommt es des Öfteren zu unterschiedlichen Ladeströmen, abhängig vom SOC.
Da wäre es sinnvoll, wenn schon eine Einstellung für max. Ampere/Pack vorhanden ist, auch den Gesamt Ladestrom zu reduzieren, wenn dieser den wert überschreitet?

**Comment by shining-man** [comment]
The change/extension is included in version 0.7.0.
