### ISSUE TITLE
Wunsch: auf allen Web-Sites einen „Home“-Button

### ISSUE THREAD

**Issue by testpaul999** [shining-man/bsc_fw#25]
Guten Tag,

ich würde mir auf allen Web-Sites einen „Home“-Button wünschen.
Am liebsten oben in der Satusleiste.
Dann muss Mann sich nicht immer „zurück-klicken“.

danke

**Comment by testpaul999** [comment]
🤩 wäre toll.
Ja habe kann selber kompilieren.
Lerne gerne dazu.
Danke

**Comment by WagnerSystems** [comment]
Hallo,
hier ein patch-File mit den Ergänzungen.
[home.patch.txt](https://github.com/shining-man/bsc_fw/files/10793370/home.patch.txt)
Ich habe das Haus Icon durch 2 Pfeile ersetzt weil ich nicht weis wie das mit den Lizenzen bei dem Icon ist.

Für ein Icon einzufügen musst du nur  `&#10094;&#10094;` durch z.B. `<img src='../home.png'>` zu ersetzen und das icon ins root vom spiffs Dateisystem zu schreiben.

**Comment by testpaul999** [comment]
Danke, ich schau mir das heute Abend mal an.👍🏻

**Comment by testpaul999** [comment]
@WagnerSystems 
Ich gebe zu das ich mit vstudio keine großen Erfahrungen habe.
Kann ich die Home.Patch automatisch „ausführen“?
Oder geht nur die tippel tappel Tour, alle files einzeln?

danke für die Unterstützung

**Comment by WagnerSystems** [comment]
Das geht über Git. 
`git apply home.patch` 
Damit werden die Änderungen in die richtigen Dateien eingetragen.

**Comment by WagnerSystems** [comment]
Kann erst heute Abend danach schauen.

**Comment by WagnerSystems** [comment]
Du musst in der letzten Zeile die Leerstelle löschen.

**Comment by testpaul999** [comment]
Sorry, nö.
![image](https://user-images.githubusercontent.com/35597907/220596974-ad45c631-e164-4d1e-ac64-7283d139f41d.jpg)

**Comment by WagnerSystems** [comment]
Versuch mal ein
`git reset --hard`
und dann den neuen Patch im Anhang
[home.patch.zip](https://github.com/shining-man/bsc_fw/files/10806169/home.patch.zip)

**Comment by testpaul999** [comment]
Hi, 
Also es blieb dabei, dass die params.h weiterhin einen Patch failed brachte params.h:525
Habe also den Teil rausgenommen und somit hat der rest geklappt.
Dann händisch die eine Zeil in der params.h geändert und rennt. :-)
Danke

**Comment by WagnerSystems** [comment]
@shining-man  Ich denke du kannst dieses Issue dann schliessen.

**Comment by testpaul999** [comment]
Hallo,
Im Prinzip ja, wäre nur schön, wenn das so übernommen wird in das nächste Release.
Weil wenn sich grundlegend etwas ändert, passt das Patch file nicht mehr.
Danke
