### ISSUE TITLE
Timeserver bitte einstellbar machen.

### ISSUE THREAD

**Issue by testpaul999** [shining-man/bsc_fw#27]
Guten Tag,
Zur Zeit ist der timeserver fest so eingestellt 
NTPClient timeClient(ntpUDP, "pool.ntp.org", 3600, 60000);
Ich habe mein ganzes Homegeraffel ohne Zugang zum Internet laufen.
Daher wäre es schön wenn ich z.b. einen internen Zeitserver eintragen kann, das am besten ohne alles neu kompilieren zu müssen. 😉
Danke

**Comment by testpaul999** [comment]
Hallo,
Naja weil‘s im Code drin ist? 😉
Und die genaue Zeit im Log und mqtt ist doch toll, oder?
Grüße

**Comment by shining-man** [comment]
Die taucht im Log aktuell nur einmal auf und zwar beim Anlauf.
Ich merke es mir aber für das nächste Release vor.

**Comment by testpaul999** [comment]
Danke
