### ISSUE TITLE
MQTT esp32Temp is logged in Fahrenheit (should be Celsius)

### ISSUE THREAD

**Issue by NemoN** [shining-man/bsc_fw#28]
<img width="294" alt="Bildschirm­foto 2023-02-22 um 12 28 04" src="https://user-images.githubusercontent.com/2212175/220607586-8374bdba-c0c3-4b3a-8a26-66ca256480bd.png">

I can touch the ESP32, so 29 Degree Celsius fits better

**Comment by NemoN** [comment]
https://gist.github.com/An-Toha/5a53f4fbe571c1b9cf02b362a83e93df

**Comment by shining-man** [comment]
Temperatur ist aus den MQTT Messages entfernt, da sie unzuverlässig ist.
