### ISSUE TITLE
Wunsch: Anzeige WLAN Verbindungsqualität auf der Main Webseite

### ISSUE THREAD

**Issue by testpaul999** [shining-man/bsc_fw#29]
Guten Tag,
Ich habe noch eine Bitte.
Da ich meinen Akku im Schuppen betreibe, wäre es toll auf der Übersichtsseite die WLAN Verbindungsqualität angezeigt zu bekommen.

Danke

**Comment by shining-man** [comment]
Is implemented in the current master branch
