### ISSUE TITLE
Wunsch: Erweiterung WebUi 

### ISSUE THREAD

**Issue by testpaul999** [shining-man/bsc_fw#33]
Ich habe einen Vorschlag für die Erweiterung des WebUi.
![wunsch-webui](https://user-images.githubusercontent.com/35597907/224136357-3de1c86a-6f9e-4274-8c04-b50dcba2af50.png)
Am besten natürlich je verbundenem BMS.
Was noch cool wäre, wenn die jeweilige Kachel beim klicken in das passende Menü springt.
Also klick auf wifi - Einstellung des wlan…
Usw.
Danke

**Comment by zippeliniot** [comment]
Moin (MikeM / Discord)  Ich weiß es ist viel Arbeit , aber hier meine Ideen: 
- bitte noch , wenn möglich, einen Nickname zum BMS zufügen - ich will mehrer DALY ( je 16S) und JK und NEEY Balanacer verwenden. Somit ist ein Überblick wichtig 
-  Währe ein iobroker Adapter eine Lösung ?

**Comment by shining-man** [comment]
Du meinst den Nickname anstatt der Nummer des BMS? 
Beispiel: "mqtt.0.BSC_TEST.bms.serial.1" -> "mqtt.0.BSC_TEST.bms.serial.JK-BMS_xyz"

**Comment by zippeliniot** [comment]
Eine Combobox währe nätürlich auch gut , mein Ziel ist es eine Struktur zu nutzen  die uU in Zukuft auc in eine Art relationales Model  einfach gewandelt werden könnten (nur so eine Erweiterungsidee). Man könnten dan eien einen Wert der Combobox gewisse daten templates verlinken. Also zB das bestimmte BMS typen unterschiedliche Parameter habne die in den Daten per Type  abgelegt werden könnte . Ich denke das im ERD Modell von Datenstrukturen (liegt daran, das ich aus dem Software- Bereich komme)

**Comment by testpaul999** [comment]
Guten Tag,

ich weiß es ist viel los rund um das bsc, aber ließe sich mein Wunsch am Web-Ui umsetzen?
Danke

**Comment by shining-man** [comment]
Ist in der v0.4.16 für serial0-2 umgesetzt
