### ISSUE TITLE
Wunsch: Backup Funktion der Einstellungen

### ISSUE THREAD

**Issue by bennyb21** [shining-man/bsc_fw#36]
Perspektivisch wäre eine Erweiterung schön, dass man die Einstellungen, die später ja komplex werden, per Backupfunktion sichern kann und auf neuer Hardware oder frisch installiertem Image importieren kann.

**Comment by pepe-el-pepe** [comment]
that would be wonderful

**Comment by tueftler0** [comment]
Schau Dir mal die 0.4.19 an. Darin gibt es die Möglichkeit nun.

**Comment by shining-man** [comment]
As a supporter, you can export and import the settings in v0.5.0
