### ISSUE TITLE
Kombinierter SOC aller BMS an WR senden

### ISSUE THREAD

**Issue by bennyb21** [shining-man/bsc_fw#37]
Ist es möglich den Durchschnittswert der SOC aller angeschlossenen BMS an den WR zu geben statt nur des Master-BMS? Bei mir unterscheiden sich die Werte immer leicht um ein paar Prozent. Der Durchschnittswert wäre da wahrscheinlich sinnvoller im Grenzbereich.

**Comment by shining-man** [comment]
Is implemented in the current master branch
