### ISSUE TITLE
Keine MQTT-Messages von nicht konfigurierten Schnittstellen

### ISSUE THREAD

**Issue by bennyb21** [shining-man/bsc_fw#38]
Es wäre schön, wenn das BSC zu nicht konfigurierten Geräten (BT oder Serial) auch keine MQTT-Messages verschickt.

Der BSC verschickt aufgrund der vielen Daten schon recht viele Nachrichten, aber insbesondere BT ist da ziemlich vorne dabei. Hier mal ein Screenshot nach einer guten Stunde Betrieb:
![Bildschirm­foto 2023-03-24 um 14 21 47](https://user-images.githubusercontent.com/57013120/227532983-de1b63a4-41ac-4715-bda1-a4bd123b5578.png)
Es ist hier kein BT Gerät konfiguriert. 
Auch eine nicht konfigurierte Serial-Verbindung schickt viele Nachrichten:
![Bildschirm­foto 2023-03-24 um 14 25 53](https://user-images.githubusercontent.com/57013120/227533283-8f03bdf5-33a6-4ee1-9b23-4d8890ab584c.png)
Allerdings kann ich auch nicht beurteilen, ab wann die Nachrichten auf welcher Hardware zu einem Problem werden. 

Danke!

**Comment by shining-man** [comment]
In dem kommenden Release sende ich nur noch von den Geräte Messages, von denen ich auch zyklisch Daten bekomme. Daher sollte dieser Fall damit dann auch abgedekt sein.
