### ISSUE TITLE
Zeitserver wird scheinbar nur bei Bootup abgerufen

### ISSUE THREAD

**Issue by tueftler0** [shining-man/bsc_fw#55]
Ich habe gerade gesehen, dass der Zeitserver scheinbar nur im Bootup abgerufen wird.
- Dann könnte z.B. die Zeit weg laufen
- Weiterhin bleibt es auf 1970 stehen, wenn der interne Zeitserver gerade nicht erreichbar war

Ich denke das sollte man öfters triggern.

**Comment by pepe-el-pepe** [comment]
Der esp32 hat scheinbar eine interne RTC ((https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/system_time.html)) die über resets hinweg die Zeit behält. Den zu nutzen wäre doch eine Idee damit die Zeit nicht erst nach dem booten und NTP Server finden korrekt ist. Eine manuelle Eingabe von Zeit und Datum wäre für alle ohne INET oder NTP Server Möglichkeit noch eine feine Option.

**Comment by tueftler0** [comment]
Mit der v0.5.4 wird der NTP nach einer Stunde abgerufen.
Somit geschlossen
