### ISSUE TITLE
Relais-Auslöseverhalten "Impuls" funktioniert nicht

### ISSUE THREAD

**Issue by tueftler0** [shining-man/bsc_fw#57]
"Impuls" bei 500ms triggert nicht.
"Permanent" funktioniert.

(Laut Shining-man hat es etwas mit der eingestellten Dauer zu tun)

**Comment by shining-man** [comment]
Alles unter 1000 ms Impuls funktioniert nicht. Als Workaround Impulslängen >= 1000 ms nutzen. Dann funktioniert der Impuls.

**Comment by shining-man** [comment]
Is in v0.5.0 solved
