### ISSUE TITLE
Discord invite link has expired

### ISSUE THREAD

**Issue by hanzoh** [shining-man/bsc_fw#69]
Hi shining-man,
the link to the Discord server in README.md has expired, could you please create a new one?

**Comment by shining-man** [comment]
The Discord is in German, but you can also write in English.
We are also happy to welcome members from other countries.
https://discord.gg/WRUhegRPQn

**Comment by cedricdelecole** [comment]
> Hi shining-man, the link to the Discord server in README.md has expired, could you please create a new one?

Hello Hanzoh, was trying to contact you about another issue for Browser_mod, sorry to "pollute" this post ... can you please contact me ?

Can't help for the discord, though ...
Many Thais in advance !!
