### ISSUE TITLE
Liste der Alarmregeln bitte optisch etwas trennen

### ISSUE THREAD

**Issue by tueftler0** [shining-man/bsc_fw#87]
Die Alarmregeln sind alle untereinander und optisch meiner Meinung nach zu wenig getrennt.
![image](https://github.com/shining-man/bsc_fw/assets/35748555/845878ef-2e45-44d7-86ae-b19cecbc315d)

**Comment by shining-man** [comment]
![grafik](https://github.com/shining-man/bsc_fw/assets/109786660/22945192-5e95-427e-b054-a603db7b17f3)
Ist etwas geändet.

**Comment by shining-man** [comment]
Änderung ist im Release v0.5.12 enthalten.

**Comment by tueftler0** [comment]
Sieht man besser
