### ISSUE TITLE
MQTT Verbindung mit Benutzername und Passwort

### ISSUE THREAD

**Issue by shining-man** [shining-man/bsc_fw#9]
### Discussed in https://github.com/shining-man/bsc_fw/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **flashy02** November 10, 2022</sup>
Hallo,
habe gerade gesehen, dass ich bei der Einstellung im Web-Interface keine Möglichkeit habe MQTT-User als auch PWD einzugeben. Soll dies noch ergänzt werden? Als Basis-Sicherheit im privaten Netzwerk finde ich dies schon sinnvoll, bzw. wäre in meinem Falle auch notwendig damit ich mich mit meinem MQTT-Broker verbinden kann.
Viele Grüße
flashy02</div>

**Comment by shining-man** [comment]
Aktuell ist tatsächlich nur eine unsichere Verbindung möglich. 
Ich werde es aber mit in das nächste Release aufnehmen.

**Comment by flashy02** [comment]
Super, danke.

**Comment by shining-man** [comment]
Funktion ist im Release v0.3.0 enthalten.
