### ISSUE TITLE
Begrenzung Max Ladespannung im Inverter Menü...

### ISSUE THREAD

**Issue by SHendrik123** [shining-man/bsc_fw#90]
Hallo.

im neuen GUI ist die max. Ladespannung auf 58.4V begrenzt. 

Bei einem 18S Akku reicht dieser Bereich nicht aus.

Viele Grüße

Hendrik

**Comment by shining-man** [comment]
Ich hab die Spannungsgrenze nach oben angehoben

**Comment by shining-man** [comment]
Änderung ist im Release v0.5.12 enthalten.
