### ISSUE TITLE
Web-Update könnte die aktuelle Version anzeigen

### ISSUE THREAD

**Issue by tueftler0** [shining-man/bsc_fw#97]
Bitte in der Update-Page auch die aktuelle Version anzeigen.
Wenn es die selbe ist, könnte auch "Kein Update vorhanden" angezeigt werden statt aller Infos zur schon installierten.

**Comment by shining-man** [comment]
Wird ab Version v0.6.0 angezeigt.

**Comment by tueftler0** [comment]
Thx
