### ISSUE TITLE
Names of Neey settings

### ISSUE THREAD

**Issue by pepe-el-pepe** [shining-man/bsc_fw#99]
hello 👋  

found something today. Shouldn't it be **buzzer** instead of **balancer**?

**Start Voltage** also sounds a bit weird. In the original Neey app it is called **Startup DifVolt**. In my humble opinion, that makes more sense or am I misunderstanding something here? 

> **German:** 
> 
> hallo 👋.
> 
> habe heute etwas gefunden. Müsste es nicht Buzzer statt Balancer heißen?
> 
> Start Voltage klingt auch etwas seltsam. In der originalen Neey-App heißt es Startup DifVolt. Meiner bescheidenen Meinung nach macht das mehr Sinn oder verstehe ich hier etwas falsch?
> 

![image](https://github.com/shining-man/bsc_fw/assets/61097309/50c7e2bf-ebb8-468c-bc0c-1eeb037373a7)

![image](https://github.com/shining-man/bsc_fw/assets/61097309/ea1b2224-3bb5-46c0-98f4-79d4a6ae6232)

**Comment by shining-man** [comment]
Nein, Balancer On ist richtig. Das hat nichts mit dem Buzzer zu tun. Die Buzzer Option ist im BSC nicht abgebildet.

**Comment by shining-man** [comment]
"Start Voltage" ist vielleicht nicht ganz glücklich gewählt. Da hast du recht.

**Comment by pepe-el-pepe** [comment]
Danke für die Richtigstellung. Das heißt, das Balancer-on/off-Setting ist gleichzusetzen mit dem Schalter „Equalizing“ von der Neey-App „Hauptseite“?
Nach meinem Empfinden ist die Position ein wenig verwirrend. Die Reihenfolge aller Einstellungen von der Neey-App ist im BSC genauso zu finden, außer die des Buzzers.
Wäre es eine Option, die Einstellung ganz oben zu platzieren, vielleicht mit ein wenig Abstand zu den anderen Werten. Dann wäre ich niemals auf die Idee mit dem Buzzer gekommen.
